# Generated by Django 4.1.2 on 2022-11-01 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_studentteachers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentTeachers',
        ),
    ]
