# Generated by Django 4.1.2 on 2022-11-01 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_delete_studentteachers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='teachers',
            new_name='teacher',
        ),
    ]
