# Generated by Django 4.1.2 on 2022-11-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_remove_student_teacher_student_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.ManyToManyField(related_name='students', to='school.teacher'),
        ),
    ]
