# Generated by Django 4.1.2 on 2022-11-02 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_alter_student_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
