# Generated by Django 4.1.2 on 2022-10-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=234, max_length=255),
            preserve_default=False,
        ),
    ]
