# Generated by Django 4.1.2 on 2022-10-27 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='slug',
        ),
    ]
